---
title: "Curriculum Vitae"
author: "MAJ Bryan Adams"
email: bryan.adams@westpoint.edu
output:
  pdf_document:
    latex_engine: xelatex
    template: C:\Users\Bryan.Adams\Desktop\GitHub\CV\svm-latex-cv.tex
  word_document: default
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
geometry: margin=1in
jobtitle: Assistant Professor, United States Military Academy
keywords: academic CV, West Point, Army
linkcolor: blue
fontawesome: yes
phone: 540-759-9339
address: 3126D Radiere Loop West Point, NY 10996
updated: no
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
\begin{center}
Updated: 16 October 2019 
\end{center}


# Education

* **M.S.**, Operations Research, *Virginia Polytechnic Institute and State University* \hfill 2017
* **B.S.**, Engineering Management, *The United States Military Academy* \hfill 2008

# Academic Experience 

* Assistant Professor, Department of Mathematical Sciences  
    *United States Military Academy* \hfill 2019-Present
* Instructor, Department of Mathematical Sciences  
    *United States Military Academy* \hfill 2017-2019
    
# Courses Written and Developed
* **MA206Y** - Introduction to Data Analysis and Statistics \hfill 2019

# Courses Directed
* **West Point**
* **MA206Y** - Introduction to Data Analysis and Statistics \hfill 2019
* **MA206** - (Assistant) Introduction to Probability and Statistics \hfill 2018-2019

# Courses Taught 
* **West Point**
* **MA206Y** - Introduction to Data Analysis and Statistics \hfill 2019
* **MA206** - Introduction to Probability and Statistics \hfill 2018 - 2019
* **MA103** - Mathematical Modeling and Introduction to Calculus \hfill 2017

# Refereed Publications

* **Adams, B.**, Fidler, K., Demoes, N., Aguiar, E., Ducharme, S., McCullough, A., Moore, C., Thomas, D., Tudor-Locke, C. (2019) Cardiometabolic thresholds for peak 30-min cadence and steps/day, *Plos One*.  https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0219933

* Langan, R., Chi, H., **Adams, B.**, Sesti, S., Paul, S., Turner, A., August, D., Carpizo, E., Kennedy, T., Grandhi, M., Alexander, H., Libutti, S., Geffner, S. (2019) Outcomes following major oncologic operations for non-AIDS defining cancers in the HIV population: A matched comparison to the general population, *World of Surgery*.  https://link.springer.com/article/10.1007/s00268-019-05151-3

* **Adams, B.**, Clark, N., Cummiskey, K., Pleuss, J., Turner, D., Watts, K. (Manuscript Under Review) Causal inference in Introductory Statistics Courses. *Journal of Statistics Education*.

* Blyman, K., Arney, K., **Adams, B.**, Hudson, T. (Abstract Accepted, Manuscript Under Review). Does your course effectively promote creativity?: Introducing the mathematical problem solving creativity rubric. *Journal of Humanistic Mathematics* - Creativity Special Issue.

* **Adams, B.**, Cummiskey, K., Jonas, B. (Abstract Accepted). Developing multivariable thinking in introductory courses using tidyverse. *Journal of Statistics Education* - Computing in the Statistics and Data Science Curriculum Special Issue.

* **Adams, B.**, Arney, K., Blyman, K., Bromberg, L., del Cuadro-Zimmerman, D. (Manuscript in Progress). Positive impacts of discovery learning assessments.

# Presentations

* **Adams, B**, Arney, K, Blyman, K, Bromberg, L, del Cuadro-Zimmerman, D. (2019). "Positive impacts of discovery learning assessments", *Joint Math Meetings*, Baltimore, MD.

* **Adams, B**, Thomas, D. (2019). "Determining mathematically based thresholds from wearable sensors: Insights from NHANES accelerometer data", *Joint Math Meetings*, Baltimore, MD. 

* **Adams, B**, Galbreath, D, Corson, W. (2019). "Written Versus Digital Feedback; Which Improves Students Learning?", *Joint Math Meetings*, Baltimore, MD.

* **Adams, B**. (2019). "Using Parking Lot Data Collection to Study Climate Science and Hot Cars in Introductory Math and Stats", *International Conference for Technology in Collegiate Mathematics*, Scottsdale, AZ.

* **Adams, B** (2018). "Using Shiny from RStudio to Teach, Motivate, and Evaluate a Classroom Created Social network", *International Conference for Technology in Collegiate Mathematics*, Washington D.C. 

* **Adams, B**, Mogensen, M. (2018). "Interactive Applets with Shiny from RStudio", *International Conference for Technology in Collegiate Mathematics*, Washington D.C.

# Webinars Presented

* **Adams, B**, Cummiskey, K. "Causal Inference in Introductory Statistics Courses: Why, What, and How?" *CAUSEweb*. https://www.causeweb.org/cause/webinar/teaching/2019-10

# Professional Memberships
* Epsilon-Mu-Eta \hfill 2008
* New York Open Statistical Meetup \hfill 2017

# Faculty Development
* Presenter| Center for Faculty Development 
* Presenter/Host | New Faculty Development Workshop

\newpage

# Student Research
* Co-Adviser, Honors Thesis. Forrester, Jenna, "Determining Relationship Between Exercise and Depression."
* Co-Adviser, Honors Thesis. Palmer, James, "Modifying the ACEER."
* Co-Adviser, Honors Thesis. Owens, Amy, "Assessing the Reliability of Algorithms to Organize and Analyze Sequencing Data."
* Co-Adviser, Senior Capstone. Murdock, Samuel, "Forecasting Key Developmental Positions in the 160th SOAR."

# Institutional and Student Developmental Service
* Developer of curriculum for first USMA introductory course in data analysis and statistics \hfill 2019
* Officer Representative, Hockey Team \hfill 2018-Present

# Community Service
* Workshop Presenter for Center for Leadership and Diversity in Science,  
Technology, Engineering, and Math \hfill 2017-Present
* Workshop presenter for Leadership Ethics and Diversity \hfill 2017-Present
* Assistant Youth Hockey Coach \hfill 2017-Present
    
# Selected Military Service
* Rose Barracks, GE \hfill 2013-2015
  * **Company Commander**, Eagle Troop, 2nd Squadron, 2nd Cavalry

* Fort Bliss, TX \hfill 2010 - 2012
  * **Company Executive Officer**, HHC, 2-5 Infantry Battalion 
  * **Platoon Leader**, C Company, 2-5 Infantry Battalion
    
# Deployments 
* Operation Enduring Freedom, Wardak, Afghanistan \hfill 2011-2012 
* Operation Enduring Freedom, Kandahar, Afghanistan \hfill 2013-2014
* Operation Atlantic Resolve, Lithuania \hfill 2015

# Selected Military Awards
* Bronze Star (2)
* Meritorious Service Medal (1)
* Army Commendation Medal (2)
* Army Achievement Medal (3)
* Ranger Tab
* Expert Infantryman Badge
* Combat Infantryman Badge
* Airborne Badge
* Air Assault Badge